name: Tests
on: [ push, pull_request ]

jobs:
  phpunit:
    name: PHP ${{ matrix.php }} on ${{ matrix.os }} (${{ matrix.dependency-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
        php: [ 8.0 ]
        dependency-version: [ 'highest', 'lowest' ]
    steps:
      - uses: actions/checkout@v2

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, fileinfo
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.dependency-version }}
          composer-options: "--no-suggest --prefer-dist"

      - name: Execute tests
        run: vendor/bin/phpunit
